{
 "title": "Slinky Oracle Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "chain_id",
    "label": "chain-id",
    "query": {
     "query": "label_values({job=\"$job\"},chain_id)"
    }
   },
   {
    "name": "ticker",
    "label": "Reported Ticker",
    "query": {
     "query": "label_values(app_prices,ticker)"
    }
   },
   {
    "name": "id",
    "label": "Side Car Price Pair",
    "query": {
     "query": "label_values(side_car_aggregated_price,id)"
    }
   },
   {
    "name": "provider",
    "label": "Data Provider",
    "query": {
     "query": "label_values(side_car_api_http_status_code,provider)"
    }
   },
   {
    "name": "provider_detailed",
    "label": "provider_detailed",
    "query": {
     "query": "label_values(side_car_provider_status_responses_per_id,provider)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary for ${chain_id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[5m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 / (rate(cometbft_consensus_latest_block_height{job=\"${job}\",chain_id=\"${chain_id}\"}[5m]))",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Total Transactions Since Restart",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "Transactions / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_num_txs{job=\"${job}\"}[5m])"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=\"${job}\"}",
     "legendFormat": "Voting Power"
    },
    {
     "expr": "avg(cometbft_consensus_validator_power{job=\"${job}\"}) / avg(cometbft_consensus_validators_power{job=\"${job}\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_state_syncing{job=\"${job}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Side Car Response % in Range",
   "type": "stat",
   "description": "The percent of requests from blockchain binary to the side car that are successful.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(app_oracle_responses{job=\"${job}\",status=\"Success\"}[$__range])) / (increase(app_oracle_responses{job=\"${job}\"}[$__range]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tickers Reported to Chain",
   "type": "stat",
   "description": "Total number of Tickers reported on-chain",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (ticker) (app_prices{job=\"${job}\",chain_id=\"${chain_id}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Oracle Responses / sec",
   "type": "stat",
   "description": "Oracle responses per second - should be 1:1 with block rate",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "/ sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(app_oracle_responses{job=\"${job}\",chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Failing Price Feeds by Provider",
   "type": "stat",
   "description": "Number of price pairs with a failure rate > 25% by provider",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (provider) ((sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\",internal_status=\"success\"}[15m]))) / (sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\"}[15m]))) < .75)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens on Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"${job}\"}"
    }
   ]
  },
  {
   "title": "Missed Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\"}[1h]))   ",
     "legendFormat": "1 Hour"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\"}[24h]))",
     "legendFormat": "1 Day"
    },
    {
     "expr": "sum(increase(cometbft_consensus_validator_missed_blocks{job=\"${job}\"}[7d]))   ",
     "legendFormat": "7 Day"
    }
   ]
  },
  { "title": "On-Chain Reported Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Reported Price by Ticker (USD)  - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "app_prices{chain_id=\"${chain_id}\",ticker=\"${ticker}\"} / 10^8",
     "legendFormat": "{{ticker}}"
    }
   ]
  },
  {
   "title": "Oracle Latency to Blockchain (s)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(app_oracle_response_latency_bucket{job=~\"${job}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Side Car Aggregated Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Side Car Aggregated Price Pair - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "side_car_aggregated_price{job=\"${job}\",id=~\"${id}\",decimals=\"8\"} / 10^8 ",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "side_car_aggregated_price{job=\"${job}\",id=~\"${id}\",decimals=\"10\"} / 10^10",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "side_car_aggregated_price{job=\"${job}\",id=~\"${id}\",decimals=\"18\"} / 10^18",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "Side Car Provider Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Data Provider HTTP 2XX % in Range",
   "type": "stat",
   "description": "Percentage of requests from sidecar to data provider that were successful in the time range of the dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider) (increase(side_car_api_http_status_code{job=\"${job}\",status_code=\"2XX\" }[$__range]))) / (sum by (provider) (increase(side_car_api_http_status_code{job=\"${job}\"}[$__range])))",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider HTTP Status Code / sec - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(side_car_api_http_status_code{job=\"${job}\",provider=~\"${provider}\"}[2m])) by (status_code,provider)",
     "legendFormat": "{{provider}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Data Provider HTTP Status Code / sec - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(side_car_api_http_status_code{job=\"${job}\",provider=~\"${provider}\"}[2m])) by (status_code,provider)",
     "legendFormat": "{{provider}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "Price Pair Requests Currently Failing > 25%",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\",internal_status=\"success\"}[15m]))) / (sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\"}[15m]))) < .75",
     "legendFormat": "{{id}} - {{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Request Success % by Price Pair and Provider - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\",id=~\"${id}\",provider=~\"${provider}\",internal_status=\"success\"}[$__range]))) / (sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\",id=~\"${id}\",provider=~\"${provider}\",}[$__range])))",
     "legendFormat": "{{id}} - {{provider}}"
    }
   ]
  },
  {
   "title": "Data Provider Request Success % by Price Pair and Provider - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\",id=~\"${id}\",provider=~\"${provider}\",internal_status=\"success\"}[$__range]))) / (sum by (provider,id) (increase(side_car_api_response_internal_status{job=\"${job}\",id=~\"${id}\",provider=~\"${provider}\",}[$__range])))",
     "legendFormat": "{{id}} - {{provider}}"
    }
   ]
  },
  { "title": "Blockchain Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Block Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{chain_id=\"${chain_id}\"}[1m]) / rate(cometbft_consensus_block_interval_seconds_count{chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{chain_id=\"${chain_id}\"}",
     "legendFormat": "Block size"
    }
   ]
  },
  {
   "title": "ABCI Method Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cometbft_abci_connection_method_timing_seconds_sum{job=\"${job}\"}[1m]) / rate(cometbft_abci_connection_method_timing_seconds_count{job=\"${job}\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "ABCI Method Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(app_abci_method_latency_sum{chain_id=\"${chain_id}\"}[1m]) / rate(app_abci_method_latency_count{chain_id=\"${chain_id}\"}[1m])",
     "legendFormat": "{{abci_method}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"${job}\",chain_id=\"${chain_id}\"}",
     "legendFormat": "Mempool"
    }
   ]
  },
  {
   "title": "Failed Transactions / sec (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_failed_txs{job=\"${job}\",chain_id=\"${chain_id}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Txs/block",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"${job}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Detailed Side Car Provider Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 }
  },
  {
   "title": "Detailed Data for ${provider_detailed} Request Success % by Price Pair, Provider and Route - Filter Above",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "repeat": "provider_detailed",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (provider,id,type) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",id=~\"${id}\",provider=~\"${provider_detailed}\",status=\"success\"}[$__range]))) / (sum by (provider,id,type) (increase(side_car_provider_status_responses_per_id{job=\"${job}\",id=~\"${id}\",provider=~\"${provider_detailed}\",}[$__range])))",
     "legendFormat": "{{id}} - {{type}}"
    }
   ]
  }
 ]
}